//! Starting the agent.
//!
//! In service mode the agent is the service's own executable started with a copy of the service's
//! SYSTEM token, retargeted to the interactive console session, on the visible desktop. The command line
//! is fixed by this module: there is no way for a caller to choose what gets executed.

use std::{ffi::c_void, io, path::Path, process::Command};
use windows::{
    core::{PCWSTR, PWSTR},
    Win32::{
        Foundation::{CloseHandle, HANDLE, WAIT_TIMEOUT},
        Security::{
            DuplicateTokenEx, SecurityImpersonation, SetTokenInformation, TokenPrimary, TokenSessionId,
            TOKEN_ALL_ACCESS,
        },
        System::{
            Environment::{CreateEnvironmentBlock, DestroyEnvironmentBlock},
            Threading::{
                CreateProcessAsUserW, GetCurrentProcess, OpenProcessToken, TerminateProcess,
                WaitForSingleObject, CREATE_NO_WINDOW, CREATE_UNICODE_ENVIRONMENT, PROCESS_INFORMATION,
                STARTUPINFOW,
            },
        },
    },
};

pub enum LaunchMode {
    /// A SYSTEM process inside the given session (the real thing, used by the installed service).
    SystemInSession(u32),
    /// The same account as the caller (development and tests without administrator rights).
    SameUser,
}

pub enum Child {
    Std(std::process::Child),
    Win { handle: HANDLE, pid: u32 },
}

// SAFETY: the process handle is only used for wait/terminate, which are thread safe.
unsafe impl Send for Child {}

impl Child {
    pub fn pid(&self) -> u32 {
        match self {
            Child::Std(c) => c.id(),
            Child::Win { pid, .. } => *pid,
        }
    }

    pub fn is_alive(&mut self) -> bool {
        match self {
            Child::Std(c) => matches!(c.try_wait(), Ok(None)),
            // SAFETY: valid process handle.
            Child::Win { handle, .. } => unsafe { WaitForSingleObject(*handle, 0) == WAIT_TIMEOUT },
        }
    }

    pub fn kill(&mut self) {
        match self {
            Child::Std(c) => {
                let _ = c.kill();
                let _ = c.wait();
            }
            // SAFETY: valid process handle owned by this value.
            Child::Win { handle, .. } => unsafe {
                let _ = TerminateProcess(*handle, 0);
            },
        }
    }
}

impl Drop for Child {
    fn drop(&mut self) {
        self.kill();
        if let Child::Win { handle, .. } = self {
            // SAFETY: closing the handle this value owns.
            unsafe {
                let _ = CloseHandle(*handle);
            }
        }
    }
}

fn wide(s: &str) -> Vec<u16> {
    s.encode_utf16().chain(std::iter::once(0)).collect()
}

fn os(e: windows::core::Error) -> io::Error {
    io::Error::other(e.to_string())
}

/// Starts `exe agent --input <pipe> --video <pipe>`. The arguments are pipe names generated by the
/// service; nothing user-supplied reaches this function.
pub fn spawn_agent(exe: &Path, input_pipe: &str, video_pipe: &str, mode: LaunchMode) -> io::Result<Child> {
    match mode {
        LaunchMode::SameUser => Ok(Child::Std(
            Command::new(exe)
                .args(["agent", "--input", input_pipe, "--video", video_pipe])
                .spawn()?,
        )),
        LaunchMode::SystemInSession(session) => {
            let cmdline = format!(
                "\"{}\" agent --input {} --video {}",
                exe.display(),
                input_pipe,
                video_pipe
            );
            // SAFETY: standard token duplication and process creation; every handle and the environment
            // block are released on every path.
            unsafe {
                let mut own = HANDLE::default();
                OpenProcessToken(GetCurrentProcess(), TOKEN_ALL_ACCESS, &mut own).map_err(os)?;
                let mut token = HANDLE::default();
                let dup = DuplicateTokenEx(
                    own,
                    TOKEN_ALL_ACCESS,
                    None,
                    SecurityImpersonation,
                    TokenPrimary,
                    &mut token,
                );
                let _ = CloseHandle(own);
                dup.map_err(os)?;
                let result = (|| -> io::Result<Child> {
                    SetTokenInformation(
                        token,
                        TokenSessionId,
                        (&session as *const u32).cast::<c_void>(),
                        std::mem::size_of::<u32>() as u32,
                    )
                    .map_err(os)?;
                    let mut env: *mut c_void = std::ptr::null_mut();
                    CreateEnvironmentBlock(&mut env, Some(token), false).map_err(os)?;
                    let mut desktop = wide(r"winsta0\default");
                    let si = STARTUPINFOW {
                        cb: std::mem::size_of::<STARTUPINFOW>() as u32,
                        lpDesktop: PWSTR(desktop.as_mut_ptr()),
                        ..Default::default()
                    };
                    let mut pi = PROCESS_INFORMATION::default();
                    let exe_w = wide(&exe.display().to_string());
                    let mut cmd_w = wide(&cmdline);
                    let created = CreateProcessAsUserW(
                        Some(token),
                        PCWSTR(exe_w.as_ptr()),
                        Some(PWSTR(cmd_w.as_mut_ptr())),
                        None,
                        None,
                        false,
                        CREATE_UNICODE_ENVIRONMENT | CREATE_NO_WINDOW,
                        Some(env),
                        PCWSTR::null(),
                        &si,
                        &mut pi,
                    );
                    let _ = DestroyEnvironmentBlock(env);
                    created.map_err(os)?;
                    let _ = CloseHandle(pi.hThread);
                    Ok(Child::Win {
                        handle: pi.hProcess,
                        pid: pi.dwProcessId,
                    })
                })();
                let _ = CloseHandle(token);
                result
            }
        }
    }
}
